/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TotpVerifyRouteImport } from './routes/totp-verify'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeniedRouteImport } from './routes/denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppPortalIndexRouteImport } from './routes/_app/portal/index'
import { Route as AppPortalIssuesRouteImport } from './routes/_app/portal/issues'
import { Route as AppPortalDocumentsRouteImport } from './routes/_app/portal/documents'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin/policies'
import { Route as AppAdminCronRouteImport } from './routes/_app/admin/cron'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppPortalIssuesIndexRouteImport } from './routes/_app/portal/issues/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppPortalIssuesIssueIdRouteImport } from './routes/_app/portal/issues/$issueId'
import { Route as AppAdminUsersGroupsRouteImport } from './routes/_app/admin/users/groups'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpVerifyRoute = TotpVerifyRouteImport.update({
  id: '/totp-verify',
  path: '/totp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeniedRoute = DeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/portal/index.lazy').then((d) => d.Route),
)
const AppPortalIssuesRoute = AppPortalIssuesRouteImport.update({
  id: '/portal/issues',
  path: '/portal/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalDocumentsRoute = AppPortalDocumentsRouteImport.update({
  id: '/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/portal/documents.lazy').then((d) => d.Route),
)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/settings.lazy').then((d) => d.Route),
)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/policies.lazy').then((d) => d.Route),
)
const AppAdminCronRoute = AppAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/cron.lazy').then((d) => d.Route),
)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppPortalIssuesIndexRoute = AppPortalIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPortalIssuesRoute,
} as any).lazy(() =>
  import('./routes/_app/portal/issues/index.lazy').then((d) => d.Route),
)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/index.lazy').then((d) => d.Route),
)
const AppPortalIssuesIssueIdRoute = AppPortalIssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => AppPortalIssuesRoute,
} as any).lazy(() =>
  import('./routes/_app/portal/issues/$issueId.lazy').then((d) => d.Route),
)
const AppAdminUsersGroupsRoute = AppAdminUsersGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/groups.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/portal/documents': typeof AppPortalDocumentsRoute
  '/portal/issues': typeof AppPortalIssuesRouteWithChildren
  '/portal/': typeof AppPortalIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/portal/issues/$issueId': typeof AppPortalIssuesIssueIdRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/portal/issues/': typeof AppPortalIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/portal/documents': typeof AppPortalDocumentsRoute
  '/portal': typeof AppPortalIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/portal/issues/$issueId': typeof AppPortalIssuesIssueIdRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/portal/issues': typeof AppPortalIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/unlock': typeof UnlockRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/cron': typeof AppAdminCronRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/portal/documents': typeof AppPortalDocumentsRoute
  '/_app/portal/issues': typeof AppPortalIssuesRouteWithChildren
  '/_app/portal/': typeof AppPortalIndexRoute
  '/_app/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/_app/portal/issues/$issueId': typeof AppPortalIssuesIssueIdRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/portal/issues/': typeof AppPortalIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/setup'
    | '/totp-verify'
    | '/unlock'
    | '/admin'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/users'
    | '/portal/documents'
    | '/portal/issues'
    | '/portal/'
    | '/admin/users/groups'
    | '/portal/issues/$issueId'
    | '/admin/users/'
    | '/portal/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/setup'
    | '/totp-verify'
    | '/unlock'
    | '/admin'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/portal/documents'
    | '/portal'
    | '/admin/users/groups'
    | '/portal/issues/$issueId'
    | '/admin/users'
    | '/portal/issues'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/denied'
    | '/error'
    | '/login'
    | '/setup'
    | '/totp-verify'
    | '/unlock'
    | '/_app/admin'
    | '/_app/admin/audit'
    | '/_app/admin/cron'
    | '/_app/admin/policies'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/portal/documents'
    | '/_app/portal/issues'
    | '/_app/portal/'
    | '/_app/admin/users/groups'
    | '/_app/portal/issues/$issueId'
    | '/_app/admin/users/'
    | '/_app/portal/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeniedRoute: typeof DeniedRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  TotpVerifyRoute: typeof TotpVerifyRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp-verify': {
      id: '/totp-verify'
      path: '/totp-verify'
      fullPath: '/totp-verify'
      preLoaderRoute: typeof TotpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denied': {
      id: '/denied'
      path: '/denied'
      fullPath: '/denied'
      preLoaderRoute: typeof DeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/issues': {
      id: '/_app/portal/issues'
      path: '/portal/issues'
      fullPath: '/portal/issues'
      preLoaderRoute: typeof AppPortalIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/documents': {
      id: '/_app/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AppPortalDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/cron': {
      id: '/_app/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AppAdminCronRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/portal/issues/': {
      id: '/_app/portal/issues/'
      path: '/'
      fullPath: '/portal/issues/'
      preLoaderRoute: typeof AppPortalIssuesIndexRouteImport
      parentRoute: typeof AppPortalIssuesRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/portal/issues/$issueId': {
      id: '/_app/portal/issues/$issueId'
      path: '/$issueId'
      fullPath: '/portal/issues/$issueId'
      preLoaderRoute: typeof AppPortalIssuesIssueIdRouteImport
      parentRoute: typeof AppPortalIssuesRoute
    }
    '/_app/admin/users/groups': {
      id: '/_app/admin/users/groups'
      path: '/groups'
      fullPath: '/admin/users/groups'
      preLoaderRoute: typeof AppAdminUsersGroupsRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersGroupsRoute: typeof AppAdminUsersGroupsRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersGroupsRoute: AppAdminUsersGroupsRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCronRoute: typeof AppAdminCronRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCronRoute: AppAdminCronRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPortalIssuesRouteChildren {
  AppPortalIssuesIssueIdRoute: typeof AppPortalIssuesIssueIdRoute
  AppPortalIssuesIndexRoute: typeof AppPortalIssuesIndexRoute
}

const AppPortalIssuesRouteChildren: AppPortalIssuesRouteChildren = {
  AppPortalIssuesIssueIdRoute: AppPortalIssuesIssueIdRoute,
  AppPortalIssuesIndexRoute: AppPortalIssuesIndexRoute,
}

const AppPortalIssuesRouteWithChildren = AppPortalIssuesRoute._addFileChildren(
  AppPortalIssuesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppPortalDocumentsRoute: typeof AppPortalDocumentsRoute
  AppPortalIssuesRoute: typeof AppPortalIssuesRouteWithChildren
  AppPortalIndexRoute: typeof AppPortalIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppPortalDocumentsRoute: AppPortalDocumentsRoute,
  AppPortalIssuesRoute: AppPortalIssuesRouteWithChildren,
  AppPortalIndexRoute: AppPortalIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeniedRoute: DeniedRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  TotpVerifyRoute: TotpVerifyRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
