/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as errorErrorRouteImport } from './routes/(error)/error'
import { Route as errorDeniedRouteImport } from './routes/(error)/denied'
import { Route as encryptionUnlockRouteImport } from './routes/(encryption)/unlock'
import { Route as encryptionSetupRouteImport } from './routes/(encryption)/setup'
import { Route as authTotpVerifyRouteImport } from './routes/(auth)/totp-verify'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppOverviewRouteRouteImport } from './routes/_app/overview/route'
import { Route as AppIssuesRouteRouteImport } from './routes/_app/issues/route'
import { Route as AppDocumentsRouteRouteImport } from './routes/_app/documents/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppIssuesIndexRouteImport } from './routes/_app/issues/index'
import { Route as AppIssuesIssueIdRouteImport } from './routes/_app/issues/$issueId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin/policies'
import { Route as AppAdminCronRouteImport } from './routes/_app/admin/cron'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminUsersGroupsRouteImport } from './routes/_app/admin/users/groups'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const errorErrorRoute = errorErrorRouteImport.update({
  id: '/(error)/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const errorDeniedRoute = errorDeniedRouteImport.update({
  id: '/(error)/denied',
  path: '/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const encryptionUnlockRoute = encryptionUnlockRouteImport.update({
  id: '/(encryption)/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const encryptionSetupRoute = encryptionSetupRouteImport.update({
  id: '/(encryption)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authTotpVerifyRoute = authTotpVerifyRouteImport.update({
  id: '/(auth)/totp-verify',
  path: '/totp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRouteRoute = AppOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/overview/route.lazy').then((d) => d.Route),
)
const AppIssuesRouteRoute = AppIssuesRouteRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRouteRoute = AppDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/route.lazy').then((d) => d.Route),
)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssuesIndexRoute = AppIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIssuesRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/issues/index.lazy').then((d) => d.Route),
)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => AppIssuesRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/issues/$issueId.lazy').then((d) => d.Route),
)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/settings.lazy').then((d) => d.Route),
)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/policies.lazy').then((d) => d.Route),
)
const AppAdminCronRoute = AppAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/cron.lazy').then((d) => d.Route),
)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/index.lazy').then((d) => d.Route),
)
const AppAdminUsersGroupsRoute = AppAdminUsersGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/groups.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/documents': typeof AppDocumentsRouteRoute
  '/issues': typeof AppIssuesRouteRouteWithChildren
  '/overview': typeof AppOverviewRouteRoute
  '/login': typeof authLoginRoute
  '/totp-verify': typeof authTotpVerifyRoute
  '/setup': typeof encryptionSetupRoute
  '/unlock': typeof encryptionUnlockRoute
  '/denied': typeof errorDeniedRoute
  '/error': typeof errorErrorRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/issues/': typeof AppIssuesIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/documents': typeof AppDocumentsRouteRoute
  '/overview': typeof AppOverviewRouteRoute
  '/login': typeof authLoginRoute
  '/totp-verify': typeof authTotpVerifyRoute
  '/setup': typeof encryptionSetupRoute
  '/unlock': typeof encryptionUnlockRoute
  '/denied': typeof errorDeniedRoute
  '/error': typeof errorErrorRoute
  '/': typeof AppIndexRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/issues': typeof AppIssuesIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/documents': typeof AppDocumentsRouteRoute
  '/_app/issues': typeof AppIssuesRouteRouteWithChildren
  '/_app/overview': typeof AppOverviewRouteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/totp-verify': typeof authTotpVerifyRoute
  '/(encryption)/setup': typeof encryptionSetupRoute
  '/(encryption)/unlock': typeof encryptionUnlockRoute
  '/(error)/denied': typeof errorDeniedRoute
  '/(error)/error': typeof errorErrorRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/cron': typeof AppAdminCronRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/_app/issues/': typeof AppIssuesIndexRoute
  '/_app/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/documents'
    | '/issues'
    | '/overview'
    | '/login'
    | '/totp-verify'
    | '/setup'
    | '/unlock'
    | '/denied'
    | '/error'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/users'
    | '/issues/$issueId'
    | '/issues/'
    | '/admin/users/groups'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/documents'
    | '/overview'
    | '/login'
    | '/totp-verify'
    | '/setup'
    | '/unlock'
    | '/denied'
    | '/error'
    | '/'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/issues/$issueId'
    | '/issues'
    | '/admin/users/groups'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/documents'
    | '/_app/issues'
    | '/_app/overview'
    | '/(auth)/login'
    | '/(auth)/totp-verify'
    | '/(encryption)/setup'
    | '/(encryption)/unlock'
    | '/(error)/denied'
    | '/(error)/error'
    | '/_app/'
    | '/_app/admin/audit'
    | '/_app/admin/cron'
    | '/_app/admin/policies'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/issues/$issueId'
    | '/_app/issues/'
    | '/_app/admin/users/groups'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authTotpVerifyRoute: typeof authTotpVerifyRoute
  encryptionSetupRoute: typeof encryptionSetupRoute
  encryptionUnlockRoute: typeof encryptionUnlockRoute
  errorDeniedRoute: typeof errorDeniedRoute
  errorErrorRoute: typeof errorErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(error)/error': {
      id: '/(error)/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof errorErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/denied': {
      id: '/(error)/denied'
      path: '/denied'
      fullPath: '/denied'
      preLoaderRoute: typeof errorDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(encryption)/unlock': {
      id: '/(encryption)/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof encryptionUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(encryption)/setup': {
      id: '/(encryption)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof encryptionSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/totp-verify': {
      id: '/(auth)/totp-verify'
      path: '/totp-verify'
      fullPath: '/totp-verify'
      preLoaderRoute: typeof authTotpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/issues/': {
      id: '/_app/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof AppIssuesIndexRouteImport
      parentRoute: typeof AppIssuesRouteRoute
    }
    '/_app/issues/$issueId': {
      id: '/_app/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppIssuesRouteRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/cron': {
      id: '/_app/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AppAdminCronRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/users/groups': {
      id: '/_app/admin/users/groups'
      path: '/groups'
      fullPath: '/admin/users/groups'
      preLoaderRoute: typeof AppAdminUsersGroupsRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersGroupsRoute: typeof AppAdminUsersGroupsRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersGroupsRoute: AppAdminUsersGroupsRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCronRoute: typeof AppAdminCronRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCronRoute: AppAdminCronRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppIssuesRouteRouteChildren {
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
  AppIssuesIndexRoute: typeof AppIssuesIndexRoute
}

const AppIssuesRouteRouteChildren: AppIssuesRouteRouteChildren = {
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
  AppIssuesIndexRoute: AppIssuesIndexRoute,
}

const AppIssuesRouteRouteWithChildren = AppIssuesRouteRoute._addFileChildren(
  AppIssuesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDocumentsRouteRoute: typeof AppDocumentsRouteRoute
  AppIssuesRouteRoute: typeof AppIssuesRouteRouteWithChildren
  AppOverviewRouteRoute: typeof AppOverviewRouteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDocumentsRouteRoute: AppDocumentsRouteRoute,
  AppIssuesRouteRoute: AppIssuesRouteRouteWithChildren,
  AppOverviewRouteRoute: AppOverviewRouteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authTotpVerifyRoute: authTotpVerifyRoute,
  encryptionSetupRoute: encryptionSetupRoute,
  encryptionUnlockRoute: encryptionUnlockRoute,
  errorDeniedRoute: errorDeniedRoute,
  errorErrorRoute: errorErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
