#!/usr/bin/env bun
// Generate docs/reference/api-routes.md from the in-process Hono routes table.
// Walks each module's `*.routes.ts` factory — no live server, no DB.
//
// Usage:
//   bun scripts/gen-api-docs.ts          # write docs/reference/api-routes.md
//   bun scripts/gen-api-docs.ts --check  # non-zero on drift
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import { Hono } from "hono";
import { accountRoutes } from "@/modules/account";
import { auditRoutes } from "@/modules/audit";
import { backupRoutes } from "@/modules/backup";
import { cronRoutes } from "@/modules/cron";
import { documentRoutes } from "@/modules/document";
import {
  encryptionProtectedRoutes,
  encryptionPublicRoutes,
  encryptionStatusRoute,
} from "@/modules/encryption";
import { fileRoutes } from "@/modules/file";
import { issueRoutes } from "@/modules/issue";
import { policyRoutes } from "@/modules/policy";
import { settingsRoutes } from "@/modules/settings";
import { systemRoutes } from "@/modules/system";

const { values: cli } = parseArgs({
  args: process.argv.slice(2),
  options: { check: { type: "boolean", default: false } },
  strict: true,
  allowPositionals: false,
});

const ROOT = resolve(import.meta.dir, "..", "..", "..");
const OUT_PATH = resolve(ROOT, "docs/reference/api-routes.md");

const app = new Hono();
app.route("/", systemRoutes());
app.route("/", encryptionStatusRoute());
app.route("/", encryptionPublicRoutes());
app.route("/", encryptionProtectedRoutes());
app.route("/", accountRoutes());
app.route("/", issueRoutes());
app.route("/", policyRoutes());
app.route("/", documentRoutes());
app.route("/", settingsRoutes());
app.route("/", auditRoutes());
app.route("/", backupRoutes());
app.route("/", cronRoutes());
app.route("/", fileRoutes());

interface HonoRoute { readonly method: string; readonly path: string }
const routesTable = (app as unknown as { routes: HonoRoute[] }).routes;

interface Row {
  readonly method: string;
  readonly path: string;
}

const SKIP_METHODS = new Set(["ALL", "HEAD", "OPTIONS"]);
const seen = new Set<string>();
const rows: Row[] = [];
for (const r of routesTable) {
  if (SKIP_METHODS.has(r.method))
    continue;
  // Drop wildcard middleware mounts.
  if (r.path === "/*" || r.path.endsWith("/*"))
    continue;
  const key = `${r.method} ${r.path}`;
  if (seen.has(key))
    continue;
  seen.add(key);
  rows.push({ method: r.method, path: `/api${r.path}` });
}
rows.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

function render(rs: readonly Row[]): string {
  const header = "# API routes (generated)\n\n"
    + "> Auto-generated by `bun run gen:api-docs` from the in-process Hono\n"
    + "> routes table. The long-form per-module narrative lives in\n"
    + "> [`api.md`](api.md); this file is the flat per-route index that CI\n"
    + "> verifies is up to date.\n\n"
    + `> ${rs.length} routes total.\n\n`
    + "| Method | Path |\n"
    + "|---|---|\n";
  const body = rs.map(r => `| ${r.method} | \`${r.path}\` |`).join("\n");
  return `${header}${body}\n`;
}

const rendered = render(rows);

if (cli.check) {
  const existing = (() => {
    try {
      return readFileSync(OUT_PATH, "utf-8");
    }
    catch {
      return "";
    }
  })();
  if (existing.trim() !== rendered.trim()) {
    console.error(`[gen-api-docs] ${OUT_PATH} is stale. Run \`bun run gen:api-docs\` and commit.`);
    process.exit(1);
  }
  console.log("[gen-api-docs] up to date");
}
else {
  writeFileSync(OUT_PATH, rendered);
  console.log(`[gen-api-docs] wrote ${OUT_PATH} (${rows.length} routes)`);
}
